/* Generated by Astilba Env. Do not edit. */
import type { BrowserProjection } from "@astilba/env/browser";

export interface Configuration {
  readonly "label": string;
}

const validText = (value: unknown, minimum: number, maximum: number): value is string => {
  if (typeof value !== "string" || value.length > maximum * 2) {
    return false;
  }
  const length = [...value].length;
  return length >= minimum && length <= maximum;
};

const decode = (
  input: Readonly<Record<string, unknown>>,
  failure: (
    code: "BOOTSTRAP_UNKNOWN_FIELD" | "BOOTSTRAP_VALUE_INVALID" | "BOOTSTRAP_VALUE_MISSING",
  ) => never,
): Readonly<Configuration> => {
  const selected = new Set(Object.freeze(["label"]));
  if (Reflect.ownKeys(input).some((key) => typeof key !== "string" || !selected.has(key))) {
    failure("BOOTSTRAP_UNKNOWN_FIELD");
  }
  const invalid = (): never => failure("BOOTSTRAP_VALUE_INVALID");
  const missing = (): never => failure("BOOTSTRAP_VALUE_MISSING");
  const values = Object.create(null) as Record<string, unknown>;

  if (!Object.hasOwn(input, "label")) {
    missing();
  }
  const raw0 = input["label"];
  if (!validText(raw0, 0, 65535)) {
    invalid();
  }
  const value0 = raw0;
  Object.defineProperty(values, "label", { enumerable: true, value: value0 });

  return Object.freeze(values) as Readonly<Configuration>;
};

const generatedProjection = Object.create(null) as Record<string, unknown>;
Object.defineProperty(generatedProjection, "codecAbi", { enumerable: true, value: "astilba.env.codec/v1" });
Object.defineProperty(generatedProjection, "consumer", { enumerable: true, value: "browser" });
Object.defineProperty(generatedProjection, "contract", { enumerable: true, value: "com.astilba.examples.next-static-shell" });
Object.defineProperty(generatedProjection, "decode", { enumerable: true, value: decode });
Object.defineProperty(generatedProjection, "digest", { enumerable: true, value: "sha256-O35OX1FFhsFP75_V-9fPTTFsBFFS_DyuYBui-q2vz54" });
Object.defineProperty(generatedProjection, "format", { enumerable: true, value: "astilba.env.projection" });
Object.defineProperty(generatedProjection, "formatVersion", { enumerable: true, value: 1 });
Object.defineProperty(generatedProjection, "generated", { enumerable: true, value: "astilba.env.generated-module/v1" });
Object.defineProperty(generatedProjection, "kind", { enumerable: true, value: "public" });
Object.defineProperty(generatedProjection, "lifecycle", { enumerable: true, value: "deployment" });
Object.defineProperty(generatedProjection, "projectionAbi", { enumerable: true, value: "astilba.env.projection/v1" });
export const projection = Object.freeze(generatedProjection) as unknown as BrowserProjection<Configuration>;
