/* Generated by Astilba Env. Do not edit. */
export interface Configuration {
  readonly "appName": string;
}

export const configuration: Readonly<Configuration> = (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "appName", { enumerable: true, value: "Env-static-shell" });
  return Object.freeze(output);
})() as Readonly<Configuration>;
