/* Generated by Astilba Env. Do not edit. */
import {
  checkProcessTarget,
  loadProcessTarget,
  type ProcessSource,
  type ProcessTargetDefinition,
} from "@astilba/env/runtime";

export interface Configuration {
  readonly "enabled": boolean;
}

const definition = (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "bindings", { enumerable: true, value: Object.freeze([(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "enabled" });
  Object.defineProperty(output, "source", { enumerable: true, value: "WORKER_ENABLED" });
  return Object.freeze(output);
})()]) });
  Object.defineProperty(output, "generated", { enumerable: true, value: "astilba.env.generated-module/v1" });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "projection", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "canonicalisation", { enumerable: true, value: "astilba.jcs/v1" });
  Object.defineProperty(output, "codecAbi", { enumerable: true, value: "astilba.env.codec/v1" });
  Object.defineProperty(output, "consumer", { enumerable: true, value: "worker" });
  Object.defineProperty(output, "contract", { enumerable: true, value: "com.astilba.examples.cloudflare-worker" });
  Object.defineProperty(output, "entries", { enumerable: true, value: Object.freeze([(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.boolean-exact/v1" });
  Object.defineProperty(output, "blank", { enumerable: true, value: "missing" });
  Object.defineProperty(output, "falseInput", { enumerable: true, value: "false" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "boolean" });
  Object.defineProperty(output, "trueInput", { enumerable: true, value: "true" });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.examples.cloudflare-worker","enabled"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "enabled" });
  Object.defineProperty(output, "required", { enumerable: true, value: true });
  Object.defineProperty(output, "visibility", { enumerable: true, value: "public" });
  return Object.freeze(output);
})()]) });
  Object.defineProperty(output, "format", { enumerable: true, value: "astilba.env.projection" });
  Object.defineProperty(output, "formatVersion", { enumerable: true, value: 1 });
  Object.defineProperty(output, "kind", { enumerable: true, value: "server" });
  Object.defineProperty(output, "projectionAbi", { enumerable: true, value: "astilba.env.projection/v1" });
  return Object.freeze(output);
})() });
  return Object.freeze(output);
})() as ProcessTargetDefinition;

export const check = (source: ProcessSource) =>
  checkProcessTarget<Configuration>(definition, source);

export const load = (source: ProcessSource): Configuration =>
  loadProcessTarget<Configuration>(definition, source);
