/* Generated by Astilba Env. Do not edit. */
import {
  checkProcessTarget,
  loadProcessTarget,
  type ProcessSource,
  type ProcessTargetDefinition,
} from "@astilba/env/runtime";

export interface Configuration {
  readonly "browserOrigin"?: string;
  readonly "label": string;
  readonly "serviceToken": string;
}

const definition = (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "bindings", { enumerable: true, value: Object.freeze([(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "browserOrigin" });
  Object.defineProperty(output, "source", { enumerable: true, value: "VITE_PUBLIC_ORIGIN" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "label" });
  Object.defineProperty(output, "source", { enumerable: true, value: "VITE_LABEL" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "serviceToken" });
  Object.defineProperty(output, "source", { enumerable: true, value: "VITE_SERVICE_TOKEN" });
  return Object.freeze(output);
})()]) });
  Object.defineProperty(output, "generated", { enumerable: true, value: "astilba.env.generated-module/v1" });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "projection", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "canonicalisation", { enumerable: true, value: "astilba.jcs/v1" });
  Object.defineProperty(output, "codecAbi", { enumerable: true, value: "astilba.env.codec/v1" });
  Object.defineProperty(output, "consumer", { enumerable: true, value: "server" });
  Object.defineProperty(output, "contract", { enumerable: true, value: "com.astilba.examples.vite" });
  Object.defineProperty(output, "entries", { enumerable: true, value: Object.freeze([(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.string-code-point/v1" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "string" });
  Object.defineProperty(output, "maxCodePoints", { enumerable: true, value: 65535 });
  Object.defineProperty(output, "minCodePoints", { enumerable: true, value: 0 });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.examples.vite","appName"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "build" });
  Object.defineProperty(output, "name", { enumerable: true, value: "appName" });
  Object.defineProperty(output, "required", { enumerable: true, value: true });
  Object.defineProperty(output, "visibility", { enumerable: true, value: "public" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.origin-ascii/v1" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "origin" });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.examples.vite","browserOrigin"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "browserOrigin" });
  Object.defineProperty(output, "required", { enumerable: true, value: false });
  Object.defineProperty(output, "visibility", { enumerable: true, value: "public" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.string-code-point/v1" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "string" });
  Object.defineProperty(output, "maxCodePoints", { enumerable: true, value: 65535 });
  Object.defineProperty(output, "minCodePoints", { enumerable: true, value: 0 });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.examples.vite","label"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "label" });
  Object.defineProperty(output, "required", { enumerable: true, value: true });
  Object.defineProperty(output, "visibility", { enumerable: true, value: "public" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.text/v1" });
  Object.defineProperty(output, "blank", { enumerable: true, value: "missing" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "text" });
  Object.defineProperty(output, "maxCodePoints", { enumerable: true, value: 65535 });
  Object.defineProperty(output, "minCodePoints", { enumerable: true, value: 1 });
  Object.defineProperty(output, "normalise", { enumerable: true, value: "preserve" });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.examples.vite","serviceToken"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "serviceToken" });
  Object.defineProperty(output, "required", { enumerable: true, value: true });
  Object.defineProperty(output, "visibility", { enumerable: true, value: "private" });
  return Object.freeze(output);
})()]) });
  Object.defineProperty(output, "format", { enumerable: true, value: "astilba.env.projection" });
  Object.defineProperty(output, "formatVersion", { enumerable: true, value: 1 });
  Object.defineProperty(output, "kind", { enumerable: true, value: "server" });
  Object.defineProperty(output, "projectionAbi", { enumerable: true, value: "astilba.env.projection/v1" });
  return Object.freeze(output);
})() });
  return Object.freeze(output);
})() as ProcessTargetDefinition;

export const check = (source: ProcessSource) =>
  checkProcessTarget<Configuration>(definition, source);

export const load = (source: ProcessSource): Configuration =>
  loadProcessTarget<Configuration>(definition, source);
