/* Generated by Astilba Env. Do not edit. */
import {
  checkProcessTarget,
  loadProcessTarget,
  type ProcessSource,
  type ProcessTargetDefinition,
} from "@astilba/env/runtime";

export interface Configuration {
  readonly "apiOrigin": string;
  readonly "serviceName": string;
}

const definition = (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "bindings", { enumerable: true, value: Object.freeze([(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "apiOrigin" });
  Object.defineProperty(output, "source", { enumerable: true, value: "SERVICE_API_ORIGIN" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "entry", { enumerable: true, value: "serviceName" });
  Object.defineProperty(output, "source", { enumerable: true, value: "SERVICE_NAME" });
  return Object.freeze(output);
})()]) });
  Object.defineProperty(output, "generated", { enumerable: true, value: "astilba.env.generated-module/v1" });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "projection", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "canonicalisation", { enumerable: true, value: "astilba.jcs/v1" });
  Object.defineProperty(output, "codecAbi", { enumerable: true, value: "astilba.env.codec/v1" });
  Object.defineProperty(output, "consumer", { enumerable: true, value: "service" });
  Object.defineProperty(output, "contract", { enumerable: true, value: "com.astilba.examples.node-service" });
  Object.defineProperty(output, "entries", { enumerable: true, value: Object.freeze([(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.origin-ascii/v1" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "origin" });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.examples.node-service","apiOrigin"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "apiOrigin" });
  Object.defineProperty(output, "required", { enumerable: true, value: true });
  Object.defineProperty(output, "visibility", { enumerable: true, value: "public" });
  return Object.freeze(output);
})(),(() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "codec", { enumerable: true, value: (() => {
  const output = Object.create(null) as Record<string, unknown>;
  Object.defineProperty(output, "abi", { enumerable: true, value: "astilba.env.text/v1" });
  Object.defineProperty(output, "blank", { enumerable: true, value: "missing" });
  Object.defineProperty(output, "kind", { enumerable: true, value: "text" });
  Object.defineProperty(output, "maxCodePoints", { enumerable: true, value: 65535 });
  Object.defineProperty(output, "minCodePoints", { enumerable: true, value: 1 });
  Object.defineProperty(output, "normalise", { enumerable: true, value: "preserve" });
  return Object.freeze(output);
})() });
  Object.defineProperty(output, "identity", { enumerable: true, value: Object.freeze(["com.astilba.examples.node-service","serviceName"]) });
  Object.defineProperty(output, "lifecycle", { enumerable: true, value: "deployment" });
  Object.defineProperty(output, "name", { enumerable: true, value: "serviceName" });
  Object.defineProperty(output, "required", { enumerable: true, value: true });
  Object.defineProperty(output, "visibility", { enumerable: true, value: "public" });
  return Object.freeze(output);
})()]) });
  Object.defineProperty(output, "format", { enumerable: true, value: "astilba.env.projection" });
  Object.defineProperty(output, "formatVersion", { enumerable: true, value: 1 });
  Object.defineProperty(output, "kind", { enumerable: true, value: "server" });
  Object.defineProperty(output, "projectionAbi", { enumerable: true, value: "astilba.env.projection/v1" });
  return Object.freeze(output);
})() });
  return Object.freeze(output);
})() as ProcessTargetDefinition;

export const check = (source: ProcessSource) =>
  checkProcessTarget<Configuration>(definition, source);

export const load = (source: ProcessSource): Configuration =>
  loadProcessTarget<Configuration>(definition, source);
